apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-stage
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: stage
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm-umbrella-chart
    repoURL: https://github.com/flamurdamoni/argo-cd-helm-values-demo
    targetRevision: HEAD
    helm:
      # https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#values-files
      valueFiles:
      - values-stage.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
